telegram_mode: false
telegram_from_user: alexbyrnes
telegram_bot_key: 914093052:AAHLyu_qXRWWlHcArd61OYKKdIiEZSVlOD4

keybase_from_user: alexbyrnes
keybase_to_user: alexbyrnes
keybase_paper_key: utility degree amused manage benefit among hip soccer happy off kiss despair hair

wallet_dir: /home/alex/evaluate/wallets/mywallet
wallet_password: pass
log_config: logging.yml
owner_endpoint: http://127.0.0.1:3420/v2/owner
