// Grin owner API
wallet_dir: /mywallet
wallet_password: change_me
owner_endpoint: http://127.0.0.1:3420/v2/owner

// Keybase
keybase_from_user: your_mobile_username // may be the same as desktop "to" user
keybase_paper_key: keybase paper key etc etc

// Telegram
telegram_mode: false
telegram_from_user: your_telegram_username
telegram_bot_key: 1234:TELEGRAM_BOT_KEY

// Logging
log_config: logging.yml
