refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d} {h({l})} {t} - {m}{n}"
  main:
    kind: file
    path: "/tmp/log/grinbot.log"
root:
  level: info
  appenders:
    - stdout
    - main
loggers:
  app::service::grin:
    level: info
    appenders:
      - main
    additive: false
